# The English text as the loaded defs hold it, in a game started in English. English lives in the Def values
# themselves: there is no English language folder, and none is needed.
# Generated by Tests/Pickle/Generate-LabelFeatures.ps1: do not edit by hand, run it again.
# Played only in the English passes; the French and Chinese twins are 05 and 06.
@en-only
Feature: the English labels and descriptions reach the loaded definitions

  Scenario: the labels a player reads in the menus
    Given the main menu is open
    Then def "FZEggBiscuit" field "label" is "egg biscuit"
    And def "FZChocolateCookies" field "label" is "chocolate chip cookie"
    And def "FZCookies" field "label" is "butter cookie"
    And def "FZBerryBiscuits" field "label" is "berry biscuit"
    And def "FZInsectJellyBiscuits" field "label" is "insect jelly biscuit"
    And def "FZRawWheat" field "label" is "wheat grain"
    And def "FZPlant_Wheat" field "label" is "wheat plant"

  Scenario: the descriptions a player reads in the information windows
    Given the main menu is open
    Then def "FZEggBiscuit" field "description" is "A plain little biscuit of wheat flour and egg. Easy to make, mildly sweet, and eaten everywhere."
    And def "FZChocolateCookies" field "description" is "A western biscuit with chocolate baked through it. It is hard to find anyone who turns one down."
    And def "FZCookies" field "description" is "A rich western cream biscuit. In some places baking them is a holiday custom: you book an hour at a cookie workshop, follow the baker's instructions, and hand the batch to the people you are fond of."
    And def "FZBerryBiscuits" field "description" is "Berries baked into the dough, a pairing that works better than it sounds. There is enough vitamin C left in them to be worth something."
    And def "FZInsectJellyBiscuits" field "description" is "A biscuit of wheat flour and insect jelly. Against all expectation it tastes of apple, and you find yourself reaching for another."
    And def "FZRawWheat" field "description" is "Threshed wheat grain. Hard to get down raw, but it bakes into every kind of biscuit."
    And def "FZPlant_Wheat" field "description" is "A grain plant grown for its seed. It is quicker to bring in than most crops, and the grain keeps well, but it is of little use until it has been baked into something."

  Scenario: the fifteen bills a player can queue at a stove
    Given the main menu is open
    Then def "CookFZEggBiscuit" field "label" is "bake egg biscuits"
    And def "Cook5FZEggBiscuit" field "label" is "bake egg biscuits x5"
    And def "Cook10FZEggBiscuit" field "label" is "bake egg biscuits x10"
    And def "CookFZChocolateCookies" field "label" is "bake chocolate chip cookies"
    And def "Cook5FZChocolateCookies" field "label" is "bake chocolate chip cookies x5"
    And def "Cook10FZChocolateCookies" field "label" is "bake chocolate chip cookies x10"
    And def "CookFZCookies" field "label" is "bake butter cookies"
    And def "Cook5FZCookies" field "label" is "bake butter cookies x5"
    And def "Cook10FZCookies" field "label" is "bake butter cookies x10"
    And def "CookFZBerryBiscuits" field "label" is "bake berry biscuits"
    And def "Cook5FZBerryBiscuits" field "label" is "bake berry biscuits x5"
    And def "Cook10FZBerryBiscuits" field "label" is "bake berry biscuits x10"
    And def "CookFZInsectJellyBiscuits" field "label" is "bake insect jelly biscuits"
    And def "Cook5FZInsectJellyBiscuits" field "label" is "bake insect jelly biscuits x5"
    And def "Cook10FZInsectJellyBiscuits" field "label" is "bake insect jelly biscuits x10"
