# The French twin of 04, read in a game started in French (-Language French). A text still in English here
# is a translation the game did not apply, whatever the offline inventory says: a language folder the game
# does not find fails silently, and the offline check only proves that the keys resolve.
# Generated by Tests/Pickle/Generate-LabelFeatures.ps1: do not edit by hand, run it again.
# Played only in the French pass.
@fr-only
Feature: the French labels and descriptions reach the loaded definitions

  Scenario: the labels a player reads in the menus
    Given the main menu is open
    Then def "FZEggBiscuit" field "label" is "biscuit à l'œuf"
    And def "FZChocolateCookies" field "label" is "cookie aux pépites de chocolat"
    And def "FZCookies" field "label" is "biscuit au beurre"
    And def "FZBerryBiscuits" field "label" is "biscuit aux baies"
    And def "FZInsectJellyBiscuits" field "label" is "biscuit à la gelée d'insecte"
    And def "FZRawWheat" field "label" is "grain de blé"
    And def "FZPlant_Wheat" field "label" is "plant de blé"

  Scenario: the descriptions a player reads in the information windows
    Given the main menu is open
    Then def "FZEggBiscuit" field "description" is "Un petit biscuit de farine de blé et d'œuf. Simple à faire, à peine sucré, et mangé partout."
    And def "FZChocolateCookies" field "description" is "Un biscuit occidental parsemé de chocolat. Difficile de trouver quelqu'un qui en refuse un."
    And def "FZCookies" field "description" is "Un riche biscuit occidental à la crème. Dans certains pays, en préparer est une coutume des fêtes : on réserve une heure dans un atelier, on suit les instructions du pâtissier, et on offre la fournée aux gens qu'on aime."
    And def "FZBerryBiscuits" field "description" is "Des baies cuites à même la pâte, un mariage qui marche mieux qu'il n'y paraît. Il y reste assez de vitamine C pour que ça compte."
    And def "FZInsectJellyBiscuits" field "description" is "Un biscuit de farine de blé et de gelée d'insecte. Contre toute attente il a un goût de pomme, et on se surprend à en reprendre un."
    And def "FZRawWheat" field "description" is "Du blé battu. Difficile à avaler cru, mais il se cuit en toutes sortes de biscuits."
    And def "FZPlant_Wheat" field "description" is "Une céréale cultivée pour son grain. Elle rentre plus vite que la plupart des cultures et se conserve bien, mais elle ne sert à rien tant qu'on n'en a rien cuit."

  Scenario: the fifteen bills a player can queue at a stove
    Given the main menu is open
    Then def "CookFZEggBiscuit" field "label" is "cuire des biscuits à l'œuf"
    And def "Cook5FZEggBiscuit" field "label" is "cuire des biscuits à l'œuf x5"
    And def "Cook10FZEggBiscuit" field "label" is "cuire des biscuits à l'œuf x10"
    And def "CookFZChocolateCookies" field "label" is "cuire des cookies aux pépites de chocolat"
    And def "Cook5FZChocolateCookies" field "label" is "cuire des cookies aux pépites de chocolat x5"
    And def "Cook10FZChocolateCookies" field "label" is "cuire des cookies aux pépites de chocolat x10"
    And def "CookFZCookies" field "label" is "cuire des biscuits au beurre"
    And def "Cook5FZCookies" field "label" is "cuire des biscuits au beurre x5"
    And def "Cook10FZCookies" field "label" is "cuire des biscuits au beurre x10"
    And def "CookFZBerryBiscuits" field "label" is "cuire des biscuits aux baies"
    And def "Cook5FZBerryBiscuits" field "label" is "cuire des biscuits aux baies x5"
    And def "Cook10FZBerryBiscuits" field "label" is "cuire des biscuits aux baies x10"
    And def "CookFZInsectJellyBiscuits" field "label" is "cuire des biscuits à la gelée d'insecte"
    And def "Cook5FZInsectJellyBiscuits" field "label" is "cuire des biscuits à la gelée d'insecte x5"
    And def "Cook10FZInsectJellyBiscuits" field "label" is "cuire des biscuits à la gelée d'insecte x10"
