# Fullzoon's own Chinese, restored under Languages/ChineseSimplified, read in a game started in Simplified
# Chinese (-Language ChineseSimplified).
# Generated by Tests/Pickle/Generate-LabelFeatures.ps1: do not edit by hand, run it again.
# Played only in the Chinese pass, and only if the install carries the language.
@zh-only
Feature: the Chinese labels and descriptions reach the loaded definitions

  Scenario: the labels a player reads in the menus
    Given the main menu is open
    Then def "FZEggBiscuit" field "label" is "鸡蛋饼干"
    And def "FZChocolateCookies" field "label" is "巧克力曲奇饼干"
    And def "FZCookies" field "label" is "曲奇饼干"
    And def "FZBerryBiscuits" field "label" is "莓果饼干"
    And def "FZInsectJellyBiscuits" field "label" is "虫胶饼干"
    And def "FZRawWheat" field "label" is "小麦"
    And def "FZPlant_Wheat" field "label" is "小麦"

  Scenario: the descriptions a player reads in the information windows
    Given the main menu is open
    Then def "FZEggBiscuit" field "description" is "由小麦粉和鸡蛋做成的小饼干，做法简单，口味甜，是一款大众小吃。"
    And def "FZChocolateCookies" field "description" is "巧克力曲奇是一种西式饼干，相当的受欢迎。"
    And def "FZCookies" field "description" is "曲奇饼干是一种西式奶油点心，在欧美，过节时，为了向爱人和朋友表示心意和尊敬，女孩子会前往曲奇作坊，在导师的督导下，亲自烘焙味道诱人的曲奇送给他们。"
    And def "FZBerryBiscuits" field "description" is "莓果饼干是常见饼干之一，莓果和饼干的搭配意外的受欢迎，莓果饼干中富含令肌肤美丽健康的维生素C，多吃也能补充维生素。"
    And def "FZInsectJellyBiscuits" field "description" is "用虫胶和小麦粉做成的饼干，竟然是苹果味的，这让你想多吃几个。"
    And def "FZRawWheat" field "description" is "小麦，生吃很难下咽，可以做成各种饼干。"
    And def "FZPlant_Wheat" field "description" is "小麦"

  Scenario: the fifteen bills a player can queue at a stove
    Given the main menu is open
    Then def "CookFZEggBiscuit" field "label" is "做鸡蛋饼干"
    And def "Cook5FZEggBiscuit" field "label" is "做鸡蛋饼干*5"
    And def "Cook10FZEggBiscuit" field "label" is "做鸡蛋饼干*10"
    And def "CookFZChocolateCookies" field "label" is "做巧克力曲奇"
    And def "Cook5FZChocolateCookies" field "label" is "做巧克力曲奇*5"
    And def "Cook10FZChocolateCookies" field "label" is "做巧克力曲奇*10"
    And def "CookFZCookies" field "label" is "做曲奇饼干"
    And def "Cook5FZCookies" field "label" is "做曲奇饼干*5"
    And def "Cook10FZCookies" field "label" is "做曲奇饼干*10"
    And def "CookFZBerryBiscuits" field "label" is "做莓果饼干"
    And def "Cook5FZBerryBiscuits" field "label" is "做莓果饼干*5"
    And def "Cook10FZBerryBiscuits" field "label" is "做莓果饼干*10"
    And def "CookFZInsectJellyBiscuits" field "label" is "做虫胶饼干"
    And def "Cook5FZInsectJellyBiscuits" field "label" is "做虫胶饼干*5"
    And def "Cook10FZInsectJellyBiscuits" field "label" is "做虫胶饼干*10"
